version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            DISK_SIZE: "16G"
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN                       
        ports:
            - 6001:5000
        volumes:
            - /volume1/docker/dsm:/storage
        restart: on-failure
        stop_grace_period: 1m
